### ISSUE TITLE
Router

### ISSUE THREAD

**Issue by PaoloCordioli** [alessandro-bugatti/ask_mvc#1]
Documentare la classe Router!!!!

**Comment by alessandro-bugatti** [comment]
Non era esattamente quello il problema, comunque adesso aggiungo una parte che dovrebbe chiarire e permettere di gestire meglio l'installazione in sottocartelle della root

**Comment by alessandro-bugatti** [comment]
Dovrebbe essere risolto con il commit #2, che oltre ad aggiungere la documentazione relativa alla fase di installazione, migliora anche il meccanismo di gestione delle sottocartelle, creando un meccanismo che ne permette l'utilizzo dei template.
