### ISSUE TITLE
Aggiungere dei bottoni per permettere la navigazione fra pagine

### ISSUE THREAD

**Issue by AndreaBegni** [alessandro-bugatti/ask_mvc#13]
Aggiungere dei bottoni che permettano di tornare indietro nelle pagine

**Comment by alessandro-bugatti** [comment]
L'ho assegnata a te, però vedi se hai tempo e voglia. Se volessi partire propongo una videochiamata prima per discutere un attimo su come impostarla (tanto per fare un po' di esercizi di progettazione) e eventualmente anche discutere di quel commento che non avevi capito bene sul salvataggio delle risposte.

**Comment by AndreaBegni** [comment]
Va benissimo, ci mettiamo d'accordo su slack magari per quando fare la videochiamata

**Comment by alessandro-bugatti** [comment]
Ok, fammi sapere
