### ISSUE TITLE
Inserire le risposte dal database nella pagina con l'elenco delle domande

### ISSUE THREAD

**Issue by alessandro-bugatti** [alessandro-bugatti/ask_mvc#15]
Attualmente la pagina principale dell'applicazione, quella che mostra le domande, mostra anche due risposte fisse che sono scritte sempre uguali e che non vengono prese dal DB. Bisogna modificarla in modo da mostrare delle risposte vere. Il metodo
```php
public static function getAllQuestions(int $answersLimit = 0) : array
```
è stato creato da @AndreaBegni in modo che il parametro *$answersLimit* limiti il numero di risposte che vengono caricate per ogni domanda. Per il momento la proposta è di mettere quel limite a 2 direttamente nella chiamata all'interno del codice, poi eventualmente verranno fatte le modifiche opportune per renderlo più intelligente. 
Nel fare questa modifica si chiede anche di modificare l'aspetto grafico delle risposte, che attualmente sono degli elenchi puntati, in modo che assumano un aspetto più carino. Inoltre adesso la scritta mostra il commento e chi l'ha scritto, direi di aggiungere anche data e ora

**Comment by GhostyJade** [comment]
penso di aver implementato correttamente tranne la parte grafica che sto pensando a qualcosa di carino...ho due domande: sulla pagina principale, per ogni domanda verranno mostrate solo 2 risposte mentre in quella specifica alla domanda ogni singola risposta? e posso modificare il file del database aggiungendo dati random per le risposte o posso fare un file a parte?

**Comment by AndreaBegni** [comment]
Non credo ci sia bisogno di modificare il file, a meno che non si voglia lasciare anche qualche risposta già di prova per quando lo si scarica. Puoi inserire i dati manualmente dal database, o dalla pagina, o facendo un file a parte.
Per quanto riguarda la parte della quantità di risposte per la pagina di una domanda specifica penso si possa pensare di caricare le risposte a blocchi, nel senso che magari ne si carica 10 poi in fondo ci sarà un bottone che permetterà di caricarne altre 10

**Comment by alessandro-bugatti** [comment]
@GhostyJade ti direi di modificare solo la pagina con tutte le domande, mettendo per il momento due risposte per ogni domande (o meno se ne hanno di meno), mentre per la pagina della singola domanda quella mostra tutte le risposte e al momento va bene così, quindi non fa parte della richiesta di questo issue
@AndreaBegni direi poi a te di modificare l'elenco delle risposte alla domanda singola, perchè è una parte che hai sviluppato tu, però ti metti d'accordo con @GhostyJade per fare in modo che l'aspetto grafico sia uguale sia nella pagina con tutte le domande sia nella pagina con una sola domanda.
Per quanto riguarda la paginazione, o comunque la gestione di un numero elevato di domande o risposte, aspetterei ancora un po', per il momento viene mostrato tutto quello che c'è.

**Comment by alessandro-bugatti** [comment]
@GhostyJade per il database se hai tempo e voglia puoi aggiungere dei dati in modo che possa essere usato come fixture per le prove, importante è che i dati siano neutri, cioè ovviamente che non abbiamo contenuti che possano urtare la sensibilità di qualcuno (lo scrivo solo per sicurezza, sicuramente non l'avresti fatto)

**Comment by GhostyJade** [comment]
Domani mattina lo faccio e carico le mie modifiche, sperando non siano brutte come penso.
Ovviamente non metto contenuti volti ad offendere la sensibilità altrui
