### ISSUE TITLE
Limitare la lunghezza delle risposte sulla home

### ISSUE THREAD

**Issue by GhostyJade** [alessandro-bugatti/ask_mvc#20]
Siccome alcuni utenti potrebbero inserire risposte davvero lunghe, si dovrebbe limitare la lunghezza delle risposte più lunghe ad un valore fisso nella preview presente nella home, in modo da aver un layout di pagina migliore da vedere

**Comment by alessandro-bugatti** [comment]
Concordo, al momento ci si potrebbe limitare a un *magic number* all'interno del codice, in modo da troncare la risposta a quella lunghezza massima e aggiungere i classici tre puntini di sospensione. Te ne fai carico tu?

**Comment by GhostyJade** [comment]
Va bene
