### ISSUE TITLE
Ordinamento risposte

### ISSUE THREAD

**Issue by alessandro-bugatti** [alessandro-bugatti/ask_mvc#25]
Mi sono accorto che le risposte nella pagina delle domande sono ordinate in un modo, mentre in quella di una specifica domanda sono ordinate in un altro (potrebbe anche essere che da una parte siano ordinate a dall'altra no, quindi l'effetto è lo stesso).
Bisogna quindi decidere qual è l'ordine che si ritiene più adatto e poi renderlo omogeneo su entrambe le pagine. 
Teoricamente mantenere l'ordine cronologico aiuta nella lettura dall'alto in basso, però nasconde le nuove risposte che rischiano di non essere viste. Voi cosa suggerite?

**Comment by GhostyJade** [comment]
nella home vengono visualizzate dalla più recente, nella pagina della singola domanda le visualizza dall'ordine di creazione...io suggerirei di avere l'ordinamento dalla più recente e specificherei nella visualizzazione, oltre al testo della risposta e all'autore anche la data di creazione...eventualmente si potrebbe poi fare un qualche tipo di filtro o ordinamento (sempre nella pagina della singola domanda)

**Comment by AndreaBegni** [comment]
Mi ero già accorto che le risposte nella domanda specifica non erano ordinate, comunque credo sia corretto ordinarle dalla più recente, poi magari si possono aggiungere dei filtri come quella con più like o cose del genere

**Comment by GhostyJade** [comment]
Esiste un issue che tratta del rating?

**Comment by AndreaBegni** [comment]
Non ancora!

**Comment by GhostyJade** [comment]
#28 aggiunta
