### ISSUE TITLE
Documentazione del codice

### ISSUE THREAD

**Issue by GhostyJade** [alessandro-bugatti/ask_mvc#29]
Sarebbe utile documentare il codice in modo che i nuovi futuri collaboratori possano capire cosa faccia ogni funzione senza dover eseguire del sano reverse engineering.

**Comment by alessandro-bugatti** [comment]
D'accordissimo, proprio ieri stato guardando che strumento usare, mi prendo io la scrittura per questa volta, l'IDE che uso mi aiuta e poi userò Doxygen (che ho già usato e che è una specie di Javadoc) per generare la documentazione. Una volta creata poi ognuno seguirà le stesse convenzioni quando ci sarà bisogno di aggiungere e/o modificare la documentazione. Se dovessi avere qualche problema sulle parti che non ho scritto io vi chiedo.

**Comment by GhostyJade** [comment]
Va bene prof
