### ISSUE TITLE
Correggere alcune problematiche

### ISSUE THREAD

**Issue by alessandro-bugatti** [alessandro-bugatti/ask_mvc#31]
Durante la scrittura della documentazione mi sono accorto dei seguenti problemi:
* la funzione saveAnswer si trova al di fuori della classe, credo sia solo una distrazione, deve essere portata dentro, oppure bisogna spiegare perchè si trova lì.
* il metodo getQuestionByID(int $id) : Question non prevede il fallimento della richiesta a fronte di un ID non presente nel database. Probabilmente inizialmente andava bene, però adesso può essere messo a posto
* Siccome la classe Connection contiene i parametri di connessione, sarebbe meglio creare un file nominato  Connection.example.php che va a finire nel repository e levare Connection.php dal tracciamento, in modo che ognuno abbia la sua copia e rimanga comunque una versione (Connection.example.php) da cui partire per fare la propria versione. Ovviamente non è rilevante per la nostra applicazione di esempio, però lo sarebbe se fosse vera, per evitare di andare a versionare i parametri di connessione reali
Questo issue è meglio poi suddividerlo in issue separati in modo da lavorare ai singoli punti uno per uno.

**Comment by AndreaBegni** [comment]
Per il primo punto, ho messo la funzione fuori dalla classe poichè per metterla all'interno, per quanto ho visto e capito, mi toccava renderla oltre che privata statica e allora a quel punto mi sembrava che tanto valesse metterla come una funzione normale all'esterno della classe.
Per il secondo punto consigliate di rimandare alla pagina principale di selezione della domanda, utilizzare come errore la pagina non trovata o crearne una nuova che mostri un errore specifico.
(forse dovremmo parlarne nell'issue dedicato)

**Comment by GhostyJade** [comment]
Per la funzione saveAnswer suggerirei di spostarla in una classe a parte e renderla singleton, per il punto due sarei per un redirect alla home ma con un errore mostrato (o un errore e "torna alla home"), per il punto 3 sarebbe utile, si si

**Comment by alessandro-bugatti** [comment]
Io farei così:
- *saveAnswer* la sposterei dentro la classe questionRepository come metodo privato statico, allo stesso modo ad esempio di *saveQuestion*, a parte che quello è pubblico
- direi che se dovesse succedere sia sufficiente una ridirezione alla home senza messaggi d'errore, negli scenari che mi immagino io il messaggio d'errore non aiuterebbe l'utente
- per il punto 3 siamo d'accordo che si possa fare senza nessuno sforzo
Proposta: se vi va bene ognuno sceglie una parte e apre un issue, la implementa come meglio crede, e poi eventualmente se ne ridiscute nell'issue, in modo che chi l'ha modificata ha studiato meglio il problema e quindi magari ha altro da dire.
Io mi prendo quello che non scegliete voi.

**Comment by GhostyJade** [comment]
Io farò la 2

**Comment by alessandro-bugatti** [comment]
Prendo io in carico il problema 1 (#34 ) e il problema 3 (#35 )

**Comment by GhostyJade** [comment]
Prof, ho notato nel correggere la mia issue che se si ridireziona l'utente ad esempio a "/ask_mvc/question/list **/** " invece di "/ask_mvc/question/list" si ottiene la pagina "Ouch, page not found"...è voluto o no?

**Comment by alessandro-bugatti** [comment]
Sì, nel senso che è il comportamento che si è voluto implementare, però modificando di poco il router potrebbero essere resi equivalenti sia **/ask_mvc/question/list/** che **/ask_mvc/question/list**. Se si ritiene che questo possa essere un comportamento desiderabile, suggerisco di correggerlo aprendo un issue separato e mettendolo a posto con un branch separato.

**Comment by alessandro-bugatti** [comment]
Chiudo questo issue perchè sono già partiti gli issue separati per risolvere i problemi evidenziati
