### ISSUE TITLE
Aggiungere una pagina per la gestione di una domanda singola

### ISSUE THREAD

**Issue by AndreaBegni** [alessandro-bugatti/ask_mvc#8]
Dare la possibilità di cliccare su una domanda per essere portati ad una nuova pagina che la visualizzi insieme a tutte le risposte a lei associate e che permetta di aggiungere nuove risposte.

**Comment by alessandro-bugatti** [comment]
Ottimo, prova a fare un branch per sviluppare questa funzionalità, che poi vediamo. Ti direi di includere il bottone con il +, che adesso è presente solo nella pagina principale che aggiunge le domande, anche alla pagina per aggiungere risposte, in modo da avere una certa omogeneità nella UI. Prima di partire con il branch aggiorna il tuo branch master con il mio, così vedi come è stato spostato il bottone nelle pagine a cui serve (mi è bastato rimuoverlo dal main.tpl e inserirlo nel content dei template a cui serve)
